kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sre-user-access
  namespace: sre
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sre-user-full-access
subjects:
- kind: Group
  namespace: sre
  name: ff234ca9-94da-4a92-a5b6-5cabd2825106
- kind: Group
  namespace: dev
  name: bd097bf2-433b-4c3b-a194-7188c3678b96