name: Generate terraform docs
on:
  - push
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Render terraform docs inside the Readme.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v0.11.0
      with:
        find-dir: ./modules